# Generated by Django 2.2.6 on 2019-12-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
