# Generated by Django 2.2.6 on 2019-12-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191224_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordeatils',
            name='Cname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitordeatils',
            name='note',
            field=models.CharField(default=3, max_length=500),
            preserve_default=False,
        ),
    ]
